Update docs and remove dodgy check for kill command
CSSUoB/TeX-Bot-Py-V2 pull request #203
Opened 2024-05-09 15:25 UTC by MattyTheHacker

2024-05-09 16:55 UTC, CarrotManMatt commented
Could you share the reasoning for removing that check? How did you know it was that one that was dodgy? What issues was it causing? Do you know why it didn't perform as expected? What was the values of the variables instead?

2024-05-09 17:58 UTC, MattyTheHacker commented
was just fucking around with it putting logging in different places and realised it never actually passed that block cos that check wasn't passing, tried removing it and it works fine. 

iirc the comparison was a Message object to an Interaction object, so it was just permanently failing.

2024-05-09 18:07 UTC, CarrotManMatt requested changes
Ah yes, I see. That's because `confirmation_message` has type `discord.Message | discord.Interaction`. It is important for us to perform this check so that we do not incorrectly assume confirmation because of a button press in the same channel that is wholly unrelated.

2024-05-09 18:07 UTC, CarrotManMatt commented on cogs/kill.py
> -                and interaction.message == confirmation_message
This check should be:

```python
and (
    interaction.message == confirmation_message
    if isinstance(confirmation_message, discord.Message)
    else interaction == confirmation_message
)
```

2024-05-09 19:39 UTC, MattyTheHacker commented on cogs/kill.py
> -                and interaction.message == confirmation_message
nope that still doesn't work

2024-05-11 01:42 UTC, CarrotManMatt commented on cogs/kill.py
> -                and interaction.message == confirmation_message
Dodgy check is fixed in #202

2024-05-11 01:44 UTC, CarrotManMatt commented
This is now dependent upon #202

2024-05-11 01:44 UTC, CarrotManMatt approved these changes

2024-05-11 16:13 UTC, LMBishop approved these changes

2024-05-11 16:14 UTC, merged