Improve the archive command
CSSUoB/TeX-Bot-Py-V2 pull request #303
Opened 2024-08-06 20:45 UTC by MattyTheHacker

2024-11-03 14:19 UTC, CarrotManMatt requested changes
Please can you provide more information about why all of the fine-grained permissions have been removed? The existing functionality ensures that the channel/category retains the correct committee permissions after archiving.

2024-11-03 14:19 UTC, CarrotManMatt commented on cogs/archive.py
> +        }
This circumvents permissions as it allows non-committee users to view channels they would not normally be able to see

2024-11-03 14:19 UTC, CarrotManMatt commented on cogs/archive.py
>          }
This circumvents permissions as it allows non-committee users to view channels they would not normally be able to see

2024-11-03 17:25 UTC, MattyTheHacker commented
The issue around users being able to see names of channels that are committee only isn't an issue, because the stats command does the same as does statbot

2024-11-03 17:28 UTC, MattyTheHacker commented
Also not sure what you mean about the permissions - this method syncs permissions to the archive channel which handles all the permissions automatically for all the channels in that category, doing it one by one in this cog is unnecessary.

2025-01-01 23:08 UTC, CarrotManMatt commented
> The issue around users being able to see names of channels that are committee only isn't an issue, because the stats command does the same as does statbot

Just because other places make some poor security decisions, doesn't mean everywhere should. I think our stats command should eventually be removed/have this viewing bug fixed (eventually™). Can the additional check of making sure the term `archive` isn't within the channel name, just be added to the current permissions checks? Is there any performance/valid usability reason for not doing the check to see if the user can view the autocomplete-suggested channel name?

2025-01-02 00:05 UTC, MattyTheHacker commented
This is now dependant on #382

2025-01-24 19:29 UTC, MattyTheHacker commented
can has review plox

2025-02-28 08:46 UTC, MattyTheHacker commented
pls

2025-03-01 11:16 UTC, CarrotManMatt commented
@MattyTheHacker you marked my comments about the removal of autocomplete permissions checking as resolved but didn't provide a response to this message: https://github.com/CSSUoB/TeX-Bot-Py-V2/pull/303#issuecomment-2567175866

2025-03-01 11:30 UTC, MattyTheHacker commented
> @MattyTheHacker you marked my comments about the removal of autocomplete permissions checking as resolved but didn't provide a response to this message: [#303 (comment)](https://github.com/CSSUoB/TeX-Bot-Py-V2/pull/303#issuecomment-2567175866)

The command is committee only so won't be visible to non-committee members therefore doesn't require additional permissions checks

2025-03-01 20:46 UTC, CarrotManMatt commented
From the development side of TeX-Bot however, we cannot guarantee that it will be deployed this way. What is the downside of including the additional check?

I am also not 100% certain that the disabling of a command within a Discord server actually prevents users sending API requests from their account to use it. I may be mistaken, however I believe that the toggle just removes it from being viewable and usable in the UI.

I would much prefer having both client & server side checks for permissions, unless there is a compelling reason that they are actively harmful if retained on the server side?

2025-03-29 11:28 UTC, CarrotManMatt requested changes
~~This feels like quite bad UX to have 2 seperate commands, rather than just performing the correct operation depending on whether the ID matches a channel or a category. We want to be as forgiving to the user as possible.~~

~~So if they just provide a category ID we archive the whole category, and if they provide a single channel ID and a category ID to move it to then we sync the permissions as necessary to match that category.~~ See https://github.com/CSSUoB/TeX-Bot-Py-V2/pull/303#pullrequestreview-2779369554

2025-03-29 11:28 UTC, CarrotManMatt commented on cogs/archive.py
> +        }
This is a duplicate of `autocomplete_get_categories()`?

2025-03-29 11:28 UTC, CarrotManMatt commented on cogs/archive.py
> +                )
```suggestion
                not isinstance(channel, discord.CategoryChannel)
                and channel.category
                and "archive" not in channel.category.name.lower()
                and isinstance(interaction_user, discord.Member)
                and channel.permissions_for(interaction_user).read_messages
```

2025-03-29 11:28 UTC, CarrotManMatt commented on cogs/archive.py
> +        if not IS_VALID_CATEGORY_ID or not IS_VALID_CHANNEL_ID:
```suggestion
        if not re.fullmatch(r"\A\d{17,20}\Z", str_category_id) or not re.fullmatch(
            r"\A\d{17,20}\Z", str_channel_id
        ):
```

2025-03-31 08:59 UTC, MattyTheHacker commented on cogs/archive.py
> +        }
it is not (granted the method names aren't the most intuitive but the doc string explains in detail)

2025-04-18 20:55 UTC, CarrotManMatt requested changes
- On line 36, `autocomplete_get_categories()` method should be renamed to `autocomplete_get_non_archival_categories()`
- Retrieval of the destination category in the `archive-channel` command should only be done after the checks for the selected channel are completed, rather than happening at the same time

After completing a more thorough review I do now see why the commands have to be separate, however I still also believe the UX may need some improvement as it's not entirely obvious from the outset as to how these should be used without understanding the implementation.

I'll be happy to approve and merge (after the requested changes in this review of course) without the improvements to the UX, but if you have any ideas they would be appreciated.

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        The list of categories only includes those that do not contain the word "archive".
```suggestion
        The set of selectable categories only includes those that do not contain the word "archive".
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        The list of categories only includes those that contain the word "archive".
```suggestion
        The set of categories only includes those that contain the word "archive".
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +    async def autocomplete_get_channels(
```suggestion
    async def autocomplete_get_non_archived_channels(
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        The list of channels will include all types of channels except categories,
```suggestion
        The list of channels will include all types of channels and categories, except those
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +                and isinstance(interaction_user, discord.Member)
```suggestion
                and isinstance(interaction_user, (discord.Member, discord.User))
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +            ephemeral=True,
```suggestion
            content=f"Archiving {category.name}...", ephemeral=True
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        for overwrite in category.overwrites:
Missing type annotation for loop variable

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        main_guild: discord.Guild = self.bot.main_guild
Missing shortcut accessor note

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +        if not (re.fullmatch(r"\A\d{17,20}\Z", str_category_id)) or not re.fullmatch(
```suggestion
        if not re.fullmatch(r"\A\d{17,20}\Z", str_category_id) or not re.fullmatch(
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +                message=f"{str_category_id!r} is not a valid category ID.",
```suggestion
                ctx=ctx, message=f"{str_category_id!r} is not a valid category ID."
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +            id=category_id,
```suggestion
            main_guild.categories, id=category_id
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +            id=channel_id,
```suggestion
            main_guild.channels, id=channel_id
```

2025-04-18 20:55 UTC, CarrotManMatt commented on cogs/archive.py
> +            return
This check should be earlier on in the flow, before the retrieval of the destination category.

2025-04-18 21:25 UTC, MattyTheHacker commented on cogs/archive.py
> +                and isinstance(interaction_user, discord.Member)
this would cause issues with permissions, surely only `Members` should be able to call it anyway?

2025-04-18 23:11 UTC, CarrotManMatt commented on cogs/archive.py
> +                and isinstance(interaction_user, discord.Member)
Hmm maybe it's better to check this once outside the loop then. Surely `channel.permissions_for()` handles being given a `User` or a `Member` and just correctly returns false? And we should rely on that behaviour in case there is some correct situation where a `User` does somehow have permissions and we don't want to miss that?

2025-04-18 23:15 UTC, MattyTheHacker commented on cogs/archive.py
> +                and isinstance(interaction_user, discord.Member)
> Surely channel.permissions_for() handles being given a User or a Member and just correctly returns false?

it does not. it only takes a Member or Role object
![image](https://github.com/user-attachments/assets/80786483-ace7-4b0a-bea0-41a3d7d8eaa6)

2025-04-20 18:03 UTC, CarrotManMatt requested changes

2025-04-20 18:03 UTC, CarrotManMatt commented on cogs/archive.py
> +            return
```suggestion
        if not re.fullmatch(r"\A\d{17,20}\Z", str_channel_id):
            await self.command_send_error(
                ctx=ctx, message=f"{str_channel_id!r} is not a valid channel ID."
            )
            return
```
Move regex validation of category ID below retrieval of channel (move to line 269).

2025-04-20 18:03 UTC, CarrotManMatt commented on cogs/archive.py
> +        category_id: int = int(str_category_id)
Move conversion of string category ID to integer category ID to after retrieval of channel (move to line 269).

2025-04-20 19:51 UTC, CarrotManMatt approved these changes

2025-04-20 19:51 UTC, CarrotManMatt commented on cogs/archive.py
> +            return
Love this. Good improvement to robustness.

2025-04-20 19:51 UTC, merged