Threads with friends
CSSUoB/TeX-Bot-Py-V2 pull request #377
Opened 2024-12-20 09:25 UTC by MattyTheHacker

couldn't think of a good name for the cog or the command so open to suggestions

2025-01-01 23:14 UTC, CarrotManMatt requested changes

2025-01-01 23:14 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +            pass
Not a big fan of this logic flow. Would it be easier to create a utility function that returns a user or role from the ID, then process the command as necessary given the returned object's type. Am happy to leave it this way if my suggestion isn't a good enough improvement.

2025-01-01 23:14 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +    )
Should everyone be able to add any arbitrary user to a thread? Or just themselves and only committee can add specific users/roles.

2025-01-01 23:14 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +            pass
Maybe it would be better to split it into individual commands for adding a user vs adding a role?

2025-01-01 23:15 UTC, CarrotManMatt commented
Love the work done here to add users without pinging them! 💚

2025-01-02 00:36 UTC, MattyTheHacker commented on cogs/thread_friends.py
> +            pass
have split into two commands

2025-01-02 00:37 UTC, MattyTheHacker commented on cogs/thread_friends.py
> +    )
Yeah i had initially left this open to everyone cos in my mind everyone can ping anyone anyway so it's not actually new functionality - but obviously that's not the case with roles, so have updated. I've also made the user command cmt locked as well on the basis that although normally a user would just be able to ping the other anyway, this command could allow them to bypass being blocked and ping the user anyway, which isn't good.

2025-01-02 23:26 UTC, CarrotManMatt requested changes

2025-01-02 23:26 UTC, CarrotManMatt commented on cogs/thread_friends.py
>          }
Missing autocomplete suggestions with `@` symbol. See previous autocomplete commands for the 2 responses that are required for each autocomplete function

2025-01-02 23:26 UTC, CarrotManMatt commented on cogs/thread_friends.py
>          }
Missing autocomplete suggestions with `@` symbol. See previous autocomplete commands for the 2 responses that are required for each autocomplete function

2025-01-02 23:27 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +        thread: discord.Thread = ctx.channel
Love the use of this check!

2025-03-01 11:40 UTC, MattyTheHacker commented
this should be ready for review now too

2025-03-01 11:47 UTC, MattyTheHacker commented
infact no scratch that i'm gonna add a config option

2025-03-01 12:11 UTC, MattyTheHacker commented
aight should be good to go

2025-03-01 21:20 UTC, CarrotManMatt requested changes
I would suggest using the full name as the name of the cog file and remove all references to "thread_friends" or "threads with friends". I think the name `cogs/add_users_to_threads_and_channels.py` is suitable.

I also request that the seperate commands for adding to threads/channels be combined into one. It is rather poor UX to have a command available that fails due to the type of channel it was called within. Surely the correct functionality can just be selected based upon whether the channel type was a thread or text channel?

2025-03-01 21:20 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +            return
* Unnecessary duplication of code
* Use of term "user" not "member"
* Allow for intersecting set of members/roles to be added

```suggestion
    async def add_member_or_role_with_ping(self, *members_and_roles: discord.Member | discord.Role, thread: discord.Thread) -> None:  # noqa: E501
        """Add a user or role to a thread and ping them."""
        members: Iterable[discord.Member] = itertools.chain.from_iterable(
            (member_or_role,)
            if isinstance(member_or_role, discord.Member)
            else member_or_role.members
            for member_or_role in members_and_roles
        )
        
        member: discord.Member
        for member in set(members):
            try:
                await thread.add_user(user=member)
            except discord.NotFound:
                logger.debug(
                    "Member: %s has blocked the bot and "
                    "therefore could not be added to thread: %s",
                    member,
                    thread
                )
```
(Requires import of itertools library)

2025-03-01 21:20 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +        await message.delete(delay=1)
Allow adding multiple users or roles to single thread
```suggestion
    async def add_user_or_role_silently(self, *users_and_roles: discord.Member | discord.Role, thread: discord.Thread) -> None:  # noqa: E501
        """Add a user or role to a thread without pinging them."""
        user_or_role: discord.Member | discord.Role
        for user_or_role in users_and_roles:
            message: discord.Message = await thread.send(
                content=f"Adding {user_or_role!r} to thread...",
                silent=True,
            )
            await message.edit(content=f"{user_or_role.mention}")
            await message.delete(delay=1)
```

2025-03-01 21:20 UTC, CarrotManMatt commented on cogs/thread_friends.py
> +            )
Remove duplicate function call by using the new multiple positional argument syntax described in suggested change to `add_user_or_role_silently()` method

2025-03-01 21:20 UTC, CarrotManMatt commented on config.py
> +        """
Remove unnecessary docstring on private method

2025-03-29 12:59 UTC, CarrotManMatt requested changes
I still believe it would be preferable to combine these two separate commands into a single one that accepts one or more members or roles, then acts accordingly.

In this case the command options would have to be updated to accept a variable number of values (this may not be possible), and the autocomplete suggestions should provide a mix of roles and members.

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            )
This event handler can be made less expensive by reordering the checks.
```suggestion
        committee_role: discord.Role = await self.bot.committee_role
        committee_elect_role: discord.Role = await self.bot.committee_elect_role

        if (
            thread.parent is None
            or thread.parent.category is None
            or "committee" not in thread.parent.category.name.lower()
            or not settings["ADD_COMMITTEE_TO_THREADS"]
        ):
            return

        await self.add_users_or_roles_silently(
            users_or_roles=[committee_role, committee_elect_role], thread=thread
        )
```

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            return
```suggestion
        member: discord.Member
        for member in users_or_roles.members:
            try:
                await thread.add_user(member)
            except discord.NotFound:
                logger.debug(
                    "User: %s has blocked the bot and "
                    "therefore could not be added to thread: %s.",
                    member,
                    thread,
                )
```

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        ):
```suggestion
        if not isinstance(ctx.channel, (discord.TextChannel, discord.Thread)):
```

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        channel: discord.TextChannel | discord.Thread = ctx.channel
Unnecessary assignment to intermediary variable. Use `ctx.channel` directly on lines 211, 219, 223, 225 & 227

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            )
I'm a bit confused why this logic is here and not part of `AddUsersToThreadsAndChannelsCommandCog.add_users_or_roles_silently()` & `AddUsersToThreadsAndChannelsCommandCog.add_users_or_roles_with_ping()`?

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +                )
I'm a bit confused why this logic is here and not part of `AddUsersToThreadsAndChannelsCommandCog.add_users_or_roles_with_ping()`?

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            content=f"User {user_to_add.mention} has been added to the channel.",
```suggestion
            content=f"Successfully added {user_to_add.mention} to the channel: {ctx.channel.mention}.",
```

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        channel: discord.TextChannel | discord.Thread = ctx.channel
Unnecessary assignment to intermediary variable. Use ctx.channel directly on lines 288, 289, 297, 301, 303 & 305

2025-03-29 12:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        role_object: discord.Role | None = discord.utils.get(main_guild.roles, id=role_id)
It's preferable to not use the term "object" in variable names. Perhaps "role_to_add"?

2025-03-30 15:07 UTC, MattyTheHacker commented
> I still believe it would be preferable to combine these two separate commands into a single one that accepts one or more members or roles, then acts accordingly.

![b4d5cab3-efb4-4ae3-b54f-b399824753df](https://github.com/user-attachments/assets/ab3b4426-81aa-473b-8cec-efa4d07091d9)

2025-03-30 15:08 UTC, MattyTheHacker commented
> I still believe it would be preferable to combine these two separate commands into a single one

![image](https://github.com/user-attachments/assets/cb939cc8-b0f7-43c4-849a-cfd11209fcc0)

2025-03-30 15:19 UTC, CarrotManMatt commented
It's been so longgggg. I forgottennn

2025-03-30 15:20 UTC, CarrotManMatt commented
I apologise for making it confusing

2025-03-30 15:25 UTC, CarrotManMatt commented
I think since the underlying logic function now accepts either object type we can unify it to a single command. If you resolve all the other comments I'll be happy to approve without this change and leave it to see how it gets used and whether it does need changing.

2025-03-30 16:41 UTC, MattyTheHacker commented on cogs/add_users_to_threads_and_channels.py
> +            return
I don't understand this diff - what's actually happening? just removing the isinstance check?

2025-03-30 16:59 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            return
Exactly that. And removing the redundant return at the end. The isinstance check is unnecessary because the type of `users_or_roles` will always be `discord.Role` by line 133, due to all the previous isinstance checks not capturing.

2025-03-30 20:10 UTC, CarrotManMatt requested changes

2025-03-30 20:10 UTC, CarrotManMatt commented on config.py
> +    def _setup_add_committee_to_threads(cls) -> None:
```suggestion
    def _setup_auto_add_committee_to_threads(cls) -> None:
```

2025-03-30 20:10 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +            users_or_roles=[committee_role, committee_elect_role], thread=thread
```suggestion
            users_or_roles=(committee_role, committee_elect_role), thread=thread
```

2025-03-31 07:02 UTC, MattyTheHacker commented on cogs/add_users_to_threads_and_channels.py
> +            )
skill issue on my part, resolved

2025-03-31 17:14 UTC, CarrotManMatt requested changes

2025-03-31 17:14 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +                return
A message is sent if the member is added to the channel, but not if the single member is added to a thread?

2025-03-31 17:16 UTC, MattyTheHacker commented on cogs/add_users_to_threads_and_channels.py
> +                return
Correct. The `add_user` method sends a message (which pings) into the thread the user is being added to when called. Text channels have no such method and so instead we have to manually add permissions and then send the message ourselves.

2025-03-31 17:16 UTC, CarrotManMatt requested changes

2025-03-31 17:16 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        description="Adds the selected role and it's users to a channel.",
```suggestion
        description="Adds the selected role and it's users to a channel or thread.",
```

2025-03-31 17:16 UTC, CarrotManMatt commented on cogs/add_users_to_threads_and_channels.py
> +        description="Adds selected users to a channel.",
```suggestion
        description="Adds selected users to a channel or thread.",
```

2025-03-31 17:19 UTC, CarrotManMatt approved these changes

2025-03-31 17:19 UTC, merged